name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: iterative/setup-cml@v2
      - env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Can use the default token for most functions
        run: |
          pip install -r requirements.txt
          python train.py --output plot.png

          echo 'My first CML report' > report.md
          echo '![](./plot.png)' >> report.md
          cml comment create --publish report.md